# Agent OS Config Generator
#
# Generates ~/agent-os/config.yml from Nix options.
# This file is declaratively managed - changes require rebuild.
#
# Reference: https://buildermethods.com/agent-os/modes

{ pkgs, options }:

let
  # Generate YAML content from options
  # Agent OS uses simple YAML structure with defaults: key
  configYaml = ''
    # Agent OS Configuration
    # Generated by Nix - do not edit manually
    # To change settings, edit modules/home-manager/ai-cli/agent-os/options.nix

    defaults:
      profile: ${options.profile}
      claude_code_commands: ${if options.claudeCodeCommands then "true" else "false"}
      use_claude_code_subagents: ${if options.useClaudeCodeSubagents then "true" else "false"}
      standards_as_claude_code_skills: ${if options.standardsAsClaudeCodeSkills then "true" else "false"}
      agent_os_commands: ${if options.agentOsCommands then "true" else "false"}
  '';
in
{
  # Home-manager file entry for config.yml
  file = {
    "agent-os/config.yml".text = configYaml;
  };
}
